blank_issues_enabled: false
contact_links:
  - name: ℹ️ Domande e chiarimenti
    url: https://github.com/floatingpurr/ita-vax-analytics/discussions
    about: Richieste di informazioni e delucidazioni su questo progetto
