name: analytics

# Schedule the run
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  # Set the job key.
  scrape-data:
    # Name of the Job
    name: Get and save analytics
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Check out a copy of this repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Install yarn
      - name: Install yarn
        run: npm install -g yarn

      # Install dependencies from yarn.lock
      - name: Install dependencies
        run: yarn install

      # Get data
      - name: Get data
        run: yarn start

      # Commit & Push
      - name: Commit a new report (if necessary)
        run: |
          echo "Checking data on: `date`"
          git config --global user.name 'GitHub Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "🔄 Refresh data on: `date`" || true
          git push
        env:
          TZ: Europe/Rome
